import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Result from "../components/Result";
import requests from "../utlis/request";
import fetch from "node-fetch";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Nav />

      <Result results={results} />
    </div>
  );
}
export async function getServerSideProps(urlProps) {
  const baseUrl = "https://api.themoviedb.org/3";
  const genre = urlProps.query.genre;

  const response = await fetch(`${baseUrl}${requests[genre]?.url || requests.fetchTrending.url}`);

  const request = await response.json();

  return {
    props: { results: request.results },
  };
}
